export const URL_HOME = '/';
export const URL_LOGIN = '/connexion';
export const URL_ADMIN_HOME = '/admin';
export const URL_REGISTER = '/inscription';
export const URL_CREATE_PRODUCT = '/creation-produit';
export const URL_USERS = '/admin/utilisateurs';
export const URL_ADMIN_RETOUR ='/admin/retour-produit'
export const URL_PRODUCTS = '/produits';
export const URL_PROFILE = '/profile'
export const URL_ADMIN_PRODUCTS = '/admin/produits';
export const URL_PRODUCT = '/produits/detail/';
export const URL_CART = '/panier';
export const URL_ADMIN_DETAIL_PRODUCT = '/admin/produits/detail';
export const URL_SUPPORT = '/support';
export const URL_SUMMARY = '/recapitulatif'